running:
  covariance: default
  score_threshold: 0.0 # 0.01
  tracker: immortal  #([immortal,cp_plus])
  max_age_since_update:
    cp_plus: 2
  min_hits_to_birth: 
    immortal: 0
    cp_plus: 0
  match_type: bipartite
  asso: iou
  asso_thres:
    giou: 1.5
    iou: 0.9
    m_dis: 11
  score_multiplier: 0.9
  gpu: False # if true num process=15, if false 150 works

data_loader:
  nms: False
  nms_thres: 0.99 # 0.1
  backward: True

merge:
  max_time_since_update: 10


# running:
#   covariance: default
#   score_threshold: 0.01
#   max_age_since_update: 2
#   min_hits_to_birth: 1
#   match_type: bipartite
#   asso: giou
#   has_velo: false
#   nms_thres: 0.1
#   motion_model: kf
#   asso_thres:
#     giou: 1.5
#     iou: 0.9
#     m_dis: 11

# redundancy:
#   mode: default
#   det_score_threshold: 
#     iou: 0.01
#     giou: 0.01
#     m_dis: 0.1
#   det_dist_threshold: 
#     iou: 0.1
#     giou: -0.5
#     m_dis: 11

# data_loader:
#   pc: false
  